## GOOGLE PLAY STORE APPS RECOMMENDATION SYSTEM

- We will use following columns ['App,
Category,
Type,
Content Rating,
Genres'] for our recommendation system.

In [1]:
import pandas as pd
import numpy as np

In [2]:
google_play_store = pd.read_csv('./googleplaystore.csv')
google_play_store.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [3]:
google_play_store.shape

(10841, 13)

In [4]:
google_play_store.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [5]:
play_store_df = google_play_store[["App", "Category", "Type", "Content Rating", "Genres"]]
play_store_df

,App,Category,Type,Content Rating,Genres
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,Free,Everyone,Art & Design
1,Coloring book moana,ART_AND_DESIGN,Free,Everyone,Art & Design;Pretend Play
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,Free,Everyone,Art & Design
3,Sketch - Draw & Paint,ART_AND_DESIGN,Free,Teen,Art & Design
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,Free,Everyone,Art & Design;Creativity
...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,Free,Everyone,Education
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,Free,Everyone,Education
10838,Parkinson Exercices FR,MEDICAL,Free,Everyone,Medical
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,Free,Mature 17+,Books & Reference
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,Free,Everyone,Lifestyle

In [6]:
play_store_df["Category"].value_counts()

Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
LIBRARIES_AND_DEMO       85
AUTO_AND_VEHICLES        85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
1.9                       1
Name: count, dtype: int64

In [7]:
# DROPPED UNNECESSARY COLUMN
play_store_df.drop(play_store_df[play_store_df['Category'] == '1.9'].index, inplace=True)

C:\Users\PC\AppData\Local\Temp\ipykernel_23048\3127619085.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  play_store_df.drop(play_store_df[play_store_df['Category'] == '1.9'].index, inplace=True)

In [8]:
play_store_df[play_store_df['Category'] == '1.9']

Empty DataFrame
Columns: [App, Category, Type, Content Rating, Genres]
Index: []

In [9]:
play_store_df.dropna(inplace=True)
play_store_df.shape

C:\Users\PC\AppData\Local\Temp\ipykernel_23048\3504169246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  play_store_df.dropna(inplace=True)

(10839, 5)

In [10]:
# So, in our 'Genres'column, we need to do some cleaning:
# - We removed all the punctuations (&,;...)
play_store_df["Genres"]

0                     Art & Design
1        Art & Design;Pretend Play
2                     Art & Design
3                     Art & Design
4          Art & Design;Creativity
                   ...
10836                    Education
10837                    Education
10838                      Medical
10839            Books & Reference
10840                    Lifestyle
Name: Genres, Length: 10839, dtype: object

In [11]:
def collapse(text):
    text = text.replace("&"," ")
    text = text.replace(";"," ")
    text = text.replace("_"," ")
    text = text.replace("  "," ")
    return text.strip()

In [12]:
play_store_df["Genres"] = play_store_df["Genres"].apply(collapse).str.lower()
play_store_df

C:\Users\PC\AppData\Local\Temp\ipykernel_23048\1641754446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  play_store_df["Genres"] = play_store_df["Genres"].apply(collapse).str.lower()

,App,Category,Type,Content Rating,Genres
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,Free,Everyone,art design
1,Coloring book moana,ART_AND_DESIGN,Free,Everyone,art design pretend play
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,Free,Everyone,art design
3,Sketch - Draw & Paint,ART_AND_DESIGN,Free,Teen,art design
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,Free,Everyone,art design creativity
...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,Free,Everyone,education
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,Free,Everyone,education
10838,Parkinson Exercices FR,MEDICAL,Free,Everyone,medical
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,Free,Mature 17+,books reference
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,Free,Everyone,lifestyle

In [13]:
play_store_df["Category"] = play_store_df["Category"].apply(collapse).str.lower()
play_store_df["App"] = play_store_df["App"].str.lower()
play_store_df["Type"] = play_store_df["Type"].str.lower()
play_store_df["Content Rating"] = play_store_df["Content Rating"].str.lower()

play_store_df

C:\Users\PC\AppData\Local\Temp\ipykernel_23048\1145693703.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  play_store_df["Category"] = play_store_df["Category"].apply(collapse).str.lower()
C:\Users\PC\AppData\Local\Temp\ipykernel_23048\1145693703.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  play_store_df["App"] = play_store_df["App"].str.lower()
C:\Users\PC\AppData\Local\Temp\ipykernel_23048\1145693703.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  play_store_df["Type"] = play_store_df["Type"].str.lower()
C:\Users\PC\AppData\Local\Temp\ipykernel_23048\1145693703.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  play_store_df["Content Rating"] = play_store_df["Content Rating"].str.lower()

,App,Category,Type,Content Rating,Genres
0,photo editor & candy camera & grid & scrapbook,art and design,free,everyone,art design
1,coloring book moana,art and design,free,everyone,art design pretend play
2,"u launcher lite – free live cool themes, hide ...",art and design,free,everyone,art design
3,sketch - draw & paint,art and design,free,teen,art design
4,pixel draw - number art coloring book,art and design,free,everyone,art design creativity
...,...,...,...,...,...
10836,sya9a maroc - fr,family,free,everyone,education
10837,fr. mike schmitz audio teachings,family,free,everyone,education
10838,parkinson exercices fr,medical,free,everyone,medical
10839,the scp foundation db fr nn5n,books and reference,free,mature 17+,books reference
10840,ihoroscope - 2018 daily horoscope & astrology,lifestyle,free,everyone,lifestyle

In [14]:
play_store_df

,App,Category,Type,Content Rating,Genres
0,photo editor & candy camera & grid & scrapbook,art and design,free,everyone,art design
1,coloring book moana,art and design,free,everyone,art design pretend play
2,"u launcher lite – free live cool themes, hide ...",art and design,free,everyone,art design
3,sketch - draw & paint,art and design,free,teen,art design
4,pixel draw - number art coloring book,art and design,free,everyone,art design creativity
...,...,...,...,...,...
10836,sya9a maroc - fr,family,free,everyone,education
10837,fr. mike schmitz audio teachings,family,free,everyone,education
10838,parkinson exercices fr,medical,free,everyone,medical
10839,the scp foundation db fr nn5n,books and reference,free,mature 17+,books reference
10840,ihoroscope - 2018 daily horoscope & astrology,lifestyle,free,everyone,lifestyle

In [15]:
play_store_df["tags"] = play_store_df["Category"] + " " + play_store_df["Type"] + " " + play_store_df["Content Rating"] + " "+ play_store_df["Genres"]
play_store_df

C:\Users\PC\AppData\Local\Temp\ipykernel_23048\1819878423.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  play_store_df["tags"] = play_store_df["Category"] + " " + play_store_df["Type"] + " " + play_store_df["Content Rating"] + " "+ play_store_df["Genres"]

,App,Category,Type,Content Rating,Genres,tags
0,photo editor & candy camera & grid & scrapbook,art and design,free,everyone,art design,art and design free everyone art design
1,coloring book moana,art and design,free,everyone,art design pretend play,art and design free everyone art design prete...
2,"u launcher lite – free live cool themes, hide ...",art and design,free,everyone,art design,art and design free everyone art design
3,sketch - draw & paint,art and design,free,teen,art design,art and design free teen art design
4,pixel draw - number art coloring book,art and design,free,everyone,art design creativity,art and design free everyone art design creat...
...,...,...,...,...,...,...
10836,sya9a maroc - fr,family,free,everyone,education,family free everyone education
10837,fr. mike schmitz audio teachings,family,free,everyone,education,family free everyone education
10838,parkinson exercices fr,medical,free,everyone,medical,medical free everyone medical
10839,the scp foundation db fr nn5n,books and reference,free,mature 17+,books reference,books and reference free mature 17+ books ref...
10840,ihoroscope - 2018 daily horoscope & astrology,lifestyle,free,everyone,lifestyle,lifestyle free everyone lifestyle

In [16]:
final_df = play_store_df[["App","tags"]]
final_df

,App,tags
0,photo editor & candy camera & grid & scrapbook,art and design free everyone art design
1,coloring book moana,art and design free everyone art design prete...
2,"u launcher lite – free live cool themes, hide ...",art and design free everyone art design
3,sketch - draw & paint,art and design free teen art design
4,pixel draw - number art coloring book,art and design free everyone art design creat...
...,...,...
10836,sya9a maroc - fr,family free everyone education
10837,fr. mike schmitz audio teachings,family free everyone education
10838,parkinson exercices fr,medical free everyone medical
10839,the scp foundation db fr nn5n,books and reference free mature 17+ books ref...
10840,ihoroscope - 2018 daily horoscope & astrology,lifestyle free everyone lifestyle

In [17]:
final_df["tags"]

0                 art and design free everyone art  design
1        art and design free everyone art  design prete...
2                 art and design free everyone art  design
3                     art and design free teen art  design
4        art and design free everyone art  design creat...
                               ...
10836                       family free everyone education
10837                       family free everyone education
10838                        medical free everyone medical
10839    books and reference free mature 17+ books  ref...
10840                    lifestyle free everyone lifestyle
Name: tags, Length: 10839, dtype: object

In [18]:
final_df.duplicated().sum()

np.int64(1102)

In [19]:
final_df.duplicated().sum()
final_df = final_df.drop_duplicates()

In [20]:
final_df = final_df.drop(final_df[(final_df["App"] == "roblox") & (final_df["tags"].str.contains("famili"))].index)

In [21]:
final_df = final_df.drop_duplicates(subset=["App"], keep="first")
final_df

,App,tags
0,photo editor & candy camera & grid & scrapbook,art and design free everyone art design
1,coloring book moana,art and design free everyone art design prete...
2,"u launcher lite – free live cool themes, hide ...",art and design free everyone art design
3,sketch - draw & paint,art and design free teen art design
4,pixel draw - number art coloring book,art and design free everyone art design creat...
...,...,...
10836,sya9a maroc - fr,family free everyone education
10837,fr. mike schmitz audio teachings,family free everyone education
10838,parkinson exercices fr,medical free everyone medical
10839,the scp foundation db fr nn5n,books and reference free mature 17+ books ref...
10840,ihoroscope - 2018 daily horoscope & astrology,lifestyle free everyone lifestyle

In [22]:
final_df.reset_index(drop=True, inplace=True)
final_df

,App,tags
0,photo editor & candy camera & grid & scrapbook,art and design free everyone art design
1,coloring book moana,art and design free everyone art design prete...
2,"u launcher lite – free live cool themes, hide ...",art and design free everyone art design
3,sketch - draw & paint,art and design free teen art design
4,pixel draw - number art coloring book,art and design free everyone art design creat...
...,...,...
9632,sya9a maroc - fr,family free everyone education
9633,fr. mike schmitz audio teachings,family free everyone education
9634,parkinson exercices fr,medical free everyone medical
9635,the scp foundation db fr nn5n,books and reference free mature 17+ books ref...
9636,ihoroscope - 2018 daily horoscope & astrology,lifestyle free everyone lifestyle

#### stemming
- NLP helps in machine understanding human language

In [23]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [24]:
def stem(text):
    lst = []

    for i in text.split():
        lst.append(ps.stem(i))

    return " ".join(lst)

In [25]:
final_df["tags"] = final_df["tags"].apply(stem)
final_df

,App,tags
0,photo editor & candy camera & grid & scrapbook,art and design free everyon art design
1,coloring book moana,art and design free everyon art design pretend...
2,"u launcher lite – free live cool themes, hide ...",art and design free everyon art design
3,sketch - draw & paint,art and design free teen art design
4,pixel draw - number art coloring book,art and design free everyon art design creativ
...,...,...
9632,sya9a maroc - fr,famili free everyon educ
9633,fr. mike schmitz audio teachings,famili free everyon educ
9634,parkinson exercices fr,medic free everyon medic
9635,the scp foundation db fr nn5n,book and refer free matur 17+ book refer
9636,ihoroscope - 2018 daily horoscope & astrology,lifestyl free everyon lifestyl

In [26]:
# Count Vectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
cv = CountVectorizer(max_features=5000)

In [28]:
vector = cv.fit_transform(final_df["tags"])

In [29]:
vector = vector.toarray()
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(9637, 77))

In [30]:
list(cv.get_feature_names_out())

['10',
 '17',
 '18',
 'action',
 'adult',
 'adventur',
 'and',
 'arcad',
 'art',
 'audio',
 'auto',
 'beauti',
 'board',
 'book',
 'brain',
 'busi',
 'card',
 'casino',
 'casual',
 'comic',
 'commun',
 'creativ',
 'date',
 'demo',
 'design',
 'drink',
 'editor',
 'educ',
 'entertain',
 'event',
 'everyon',
 'famili',
 'financ',
 'fit',
 'food',
 'free',
 'game',
 'health',
 'home',
 'hous',
 'librari',
 'lifestyl',
 'local',
 'magazin',
 'map',
 'matur',
 'medic',
 'music',
 'navig',
 'news',
 'onli',
 'paid',
 'parent',
 'person',
 'photographi',
 'play',
 'player',
 'pretend',
 'product',
 'puzzl',
 'race',
 'refer',
 'role',
 'shop',
 'simul',
 'social',
 'sport',
 'strategi',
 'teen',
 'tool',
 'travel',
 'trivia',
 'unrat',
 'vehicl',
 'video',
 'weather',
 'word']

In [31]:
final_df.shape

(9637, 2)

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

In [33]:
similarity = cosine_similarity(vector)
similarity.shape

(9637, 9637)

In [34]:
# AS OF NOW, WE HAVE COMPLETED SOME CLEANING, STEMMING AND VECTORIZATION

# NEXT STEP IS TO REMOVE DUPLICATED VALUES

#start working on dealing with duplicate values and later on move with the plan

In [35]:
## Recommendation step

final_df[final_df["App"] == "facebook"]

           App                     tags
2002  facebook  social free teen social

In [36]:
vector[2002]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
app_index = final_df[final_df["App"] == "netflix"].index
app_index

Index([691], dtype='int64')

In [38]:
app_index = final_df[final_df["App"] == "netflix"].index[0]
app_index

np.int64(691)

In [39]:
# we will save similarity of 'netflix' movie in distances. Folling is the similarity score of 'netflix' with other vectors.

distances = similarity[app_index]
distances

array([0.12309149, 0.1132277 , 0.12309149, ..., 0.16666667, 0.11785113,
       0.16666667], shape=(9637,))

In [40]:
# By applying enumarte function, it assigned each value index number
    
index_list = list(enumerate(distances))
index_list

[(0, np.float64(0.12309149097933275)),
 (1, np.float64(0.11322770341445959)),
 (2, np.float64(0.12309149097933275)),
 (3, np.float64(0.2461829819586655)),
 (4, np.float64(0.11785113019775795)),
 (5, np.float64(0.12309149097933275)),
 (6, np.float64(0.12309149097933275)),
 (7, np.float64(0.12309149097933275)),
 (8, np.float64(0.12309149097933275)),
 (9, np.float64(0.11785113019775795)),
 (10, np.float64(0.12309149097933275)),
 (11, np.float64(0.12309149097933275)),
 (12, np.float64(0.2461829819586655)),
 (13, np.float64(0.12309149097933275)),
 (14, np.float64(0.12309149097933275)),
 (15, np.float64(0.12309149097933275)),
 (16, np.float64(0.12309149097933275)),
 (17, np.float64(0.12309149097933275)),
 (18, np.float64(0.12309149097933275)),
 (19, np.float64(0.12309149097933275)),
 (20, np.float64(0.12309149097933275)),
 (21, np.float64(0.12309149097933275)),
 (22, np.float64(0.11785113019775795)),
 (23, np.float64(0.11322770341445959)),
 (24, np.float64(0.12309149097933275)),
 (25, np.float64(0.12309149097933275)),
 (26, np.float64(0.11785113019775795)),
 (27, np.float64(0.12309149097933275)),
 (28, np.float64(0.12309149097933275)),
 (29, np.float64(0.12309149097933275)),
 (30, np.float64(0.12309149097933275)),
 (31, np.float64(0.12309149097933275)),
 (32, np.float64(0.12309149097933275)),
 (33, np.float64(0.12309149097933275)),
 (34, np.float64(0.2461829819586655)),
 (35, np.float64(0.12309149097933275)),
 (36, np.float64(0.11785113019775795)),
 (37, np.float64(0.12309149097933275)),
 (38, np.float64(0.12309149097933275)),
 (39, np.float64(0.12309149097933275)),
 (40, np.float64(0.12309149097933275)),
 (41, np.float64(0.12309149097933275)),
 (42, np.float64(0.12309149097933275)),
 (43, np.float64(0.11785113019775795)),
 (44, np.float64(0.12309149097933275)),
 (45, np.float64(0.12309149097933275)),
 (46, np.float64(0.12309149097933275)),
 (47, np.float64(0.12309149097933275)),
 (48, np.float64(0.12309149097933275)),
 (49, np.float64(0.12309149097933275)),
 (50, np.float64(0.12309149097933275)),
 (51, np.float64(0.12309149097933275)),
 (52, np.float64(0.12309149097933275)),
 (53, np.float64(0.12309149097933275)),
 (54, np.float64(0.12309149097933275)),
 (55, np.float64(0.12309149097933275)),
 (56, np.float64(0.12309149097933275)),
 (57, np.float64(0.12309149097933275)),
 (58, np.float64(0.12309149097933275)),
 (59, np.float64(0.12309149097933275)),
 (60, np.float64(0.12309149097933275)),
 (61, np.float64(0.12309149097933275)),
 (62, np.float64(0.12309149097933275)),
 (63, np.float64(0.12309149097933275)),
 (64, np.float64(0.12309149097933275)),
 (65, np.float64(0.12309149097933275)),
 (66, np.float64(0.12309149097933275)),
 (67, np.float64(0.12309149097933275)),
 (68, np.float64(0.12309149097933275)),
 (69, np.float64(0.12309149097933275)),
 (70, np.float64(0.12309149097933275)),
 (71, np.float64(0.12309149097933275)),
 (72, np.float64(0.2461829819586655)),
 (73, np.float64(0.12309149097933275)),
 (74, np.float64(0.12309149097933275)),
 (75, np.float64(0.12309149097933275)),
 (76, np.float64(0.12309149097933275)),
 (77, np.float64(0.11785113019775795)),
 (78, np.float64(0.12309149097933275)),
 (79, np.float64(0.12309149097933275)),
 (80, np.float64(0.12309149097933275)),
 (81, np.float64(0.12309149097933275)),
 (82, np.float64(0.12309149097933275)),
 (83, np.float64(0.12309149097933275)),
 (84, np.float64(0.12309149097933275)),
 (85, np.float64(0.12309149097933275)),
 (86, np.float64(0.12309149097933275)),
 (87, np.float64(0.12309149097933275)),
 (88, np.float64(0.12309149097933275)),
 (89, np.float64(0.12309149097933275)),
 (90, np.float64(0.12309149097933275)),
 (91, np.float64(0.12309149097933275)),
 (92, np.float64(0.12309149097933275)),
 (93, np.float64(0.12309149097933275)),
 (94, np.float64(0.12309149097933275)),
 (95, np.float64(0.12309149097933275)),
 (96, np.float64(0.12309149097933275)),
 (97, np.float64(0.12309149097933275)),
 (98, np.float64(0.1666666666666667)),
 (99, np.float64(0.1666666666666667)),
 (100, np.float64(0.1666666666666667)),
 (101, np.float64(0.1666666666666667)),
 (102, np.float64(0.1666666666666667)),
 (103, np.float64(0.1666666666666667)),
 (104, np.float64(0.1666666666666667)),
 (105, np.float64(0.1666666666666667)),
 (106, np.float64(0.1666666666666667)),
 (107, np.float64(0.1666666666666667)),
 (108, np.float64(0.1666666666666667)),
 (109, np.float64(0.1666666666666667)),
 (110, np.float64(0.1666666666666667)),
 (111, np.float64(0.1666666666666667)),
 (112, np.float64(0.3333333333333334)),
 (113, np.float64(0.1543033499620919)),
 (114, np.float64(0.1666666666666667)),
 (115, np.float64(0.1666666666666667)),
 (116, np.float64(0.1666666666666667)),
 (117, np.float64(0.1666666666666667)),
 (118, np.float64(0.1666666666666667)),
 (119, np.float64(0.1666666666666667)),
 (120, np.float64(0.1666666666666667)),
 (121, np.float64(0.1666666666666667)),
 (122, np.float64(0.1666666666666667)),
 (123, np.float64(0.1666666666666667)),
 (124, np.float64(0.1666666666666667)),
 (125, np.float64(0.1666666666666667)),
 (126, np.float64(0.3333333333333334)),
 (127, np.float64(0.1666666666666667)),
 (128, np.float64(0.1666666666666667)),
 (129, np.float64(0.1543033499620919)),
 (130, np.float64(0.1543033499620919)),
 (131, np.float64(0.1666666666666667)),
 (132, np.float64(0.1666666666666667)),
 (133, np.float64(0.1543033499620919)),
 (134, np.float64(0.1543033499620919)),
 (135, np.float64(0.1666666666666667)),
 (136, np.float64(0.1666666666666667)),
 (137, np.float64(0.1666666666666667)),
 (138, np.float64(0.1666666666666667)),
 (139, np.float64(0.2461829819586655)),
 (140, np.float64(0.12309149097933275)),
 (141, np.float64(0.11785113019775795)),
 (142, np.float64(0.12309149097933275)),
 (143, np.float64(0.2461829819586655)),
 (144, np.float64(0.12309149097933275)),
 (145, np.float64(0.12309149097933275)),
 (146, np.float64(0.2461829819586655)),
 (147, np.float64(0.12309149097933275)),
 (148, np.float64(0.2461829819586655)),
 (149, np.float64(0.12309149097933275)),
 (150, np.float64(0.12309149097933275)),
 (151, np.float64(0.2461829819586655)),
 (152, np.float64(0.2461829819586655)),
 (153, np.float64(0.12309149097933275)),
 (154, np.float64(0.12309149097933275)),
 (155, np.float64(0.12309149097933275)),
 (156, np.float64(0.12309149097933275)),
 (157, np.float64(0.2461829819586655)),
 (158, np.float64(0.12309149097933275)),
 (159, np.float64(0.12309149097933275)),
 (160, np.float64(0.12309149097933275)),
 (161, np.float64(0.12309149097933275)),
 (162, np.float64(0.12309149097933275)),
 (163, np.float64(0.12309149097933275)),
 (164, np.float64(0.12309149097933275)),
 (165, np.float64(0.2461829819586655)),
 (166, np.float64(0.11785113019775795)),
 (167, np.float64(0.12309149097933275)),
 (168, np.float64(0.12309149097933275)),
 (169, np.float64(0.12309149097933275)),
 (170, np.float64(0.11785113019775795)),
 (171, np.float64(0.12309149097933275)),
 (172, np.float64(0.12309149097933275)),
 (173, np.float64(0.12309149097933275)),
 (174, np.float64(0.12309149097933275)),
 (175, np.float64(0.12309149097933275)),
 (176, np.float64(0.12309149097933275)),
 (177, np.float64(0.12309149097933275)),
 (178, np.float64(0.12309149097933275)),
 (179, np.float64(0.12309149097933275)),
 (180, np.float64(0.12309149097933275)),
 (181, np.float64(0.12309149097933275)),
 (182, np.float64(0.12309149097933275)),
 (183, np.float64(0.12309149097933275)),
 (184, np.float64(0.12309149097933275)),
 (185, np.float64(0.12309149097933275)),
 (186, np.float64(0.11785113019775795)),
 (187, np.float64(0.1666666666666667)),
 (188, np.float64(0.1666666666666667)),
 (189, np.float64(0.1666666666666667)),
 (190, np.float64(0.1666666666666667)),
 (191, np.float64(0.1666666666666667)),
 (192, np.float64(0.1666666666666667)),
 (193, np.float64(0.1666666666666667)),
 (194, np.float64(0.1666666666666667)),
 (195, np.float64(0.1666666666666667)),
 (196, np.float64(0.1666666666666667)),
 (197, np.float64(0.1666666666666667)),
 (198, np.float64(0.1666666666666667)),
 (199, np.float64(0.1666666666666667)),
 (200, np.float64(0.1666666666666667)),
 (201, np.float64(0.1666666666666667)),
 (202, np.float64(0.1666666666666667)),
 (203, np.float64(0.1666666666666667)),
 (204, np.float64(0.1666666666666667)),
 (205, np.float64(0.1666666666666667)),
 (206, np.float64(0.1666666666666667)),
 (207, np.float64(0.1666666666666667)),
 (208, np.float64(0.1666666666666667)),
 (209, np.float64(0.1666666666666667)),
 (210, np.float64(0.1666666666666667)),
 (211, np.float64(0.1666666666666667)),
 (212, np.float64(0.1666666666666667)),
 (213, np.float64(0.1666666666666667)),
 (214, np.float64(0.1666666666666667)),
 (215, np.float64(0.1666666666666667)),
 (216, np.float64(0.1666666666666667)),
 (217, np.float64(0.1666666666666667)),
 (218, np.float64(0.1666666666666667)),
 (219, np.float64(0.1666666666666667)),
 (220, np.float64(0.1666666666666667)),
 (221, np.float64(0.1666666666666667)),
 (222, np.float64(0.1666666666666667)),
 (223, np.float64(0.1666666666666667)),
 (224, np.float64(0.1666666666666667)),
 (225, np.float64(0.1666666666666667)),
 (226, np.float64(0.1666666666666667)),
 (227, np.float64(0.1666666666666667)),
 (228, np.float64(0.1666666666666667)),
 (229, np.float64(0.1666666666666667)),
 (230, np.float64(0.1666666666666667)),
 (231, np.float64(0.1666666666666667)),
 (232, np.float64(0.1666666666666667)),
 (233, np.float64(0.0)),
 (234, np.float64(0.0)),
 (235, np.float64(0.1666666666666667)),
 (236, np.float64(0.1666666666666667)),
 (237, np.float64(0.1666666666666667)),
 (238, np.float64(0.1666666666666667)),
 (239, np.float64(0.1666666666666667)),
 (240, np.float64(0.1666666666666667)),
 (241, np.float64(0.1666666666666667)),
 (242, np.float64(0.1666666666666667)),
 (243, np.float64(0.1666666666666667)),
 (244, np.float64(0.1666666666666667)),
 (245, np.float64(0.1666666666666667)),
 (246, np.float64(0.1666666666666667)),
 (247, np.float64(0.1666666666666667)),
 (248, np.float64(0.1666666666666667)),
 (249, np.float64(0.1666666666666667)),
 (250, np.float64(0.1666666666666667)),
 (251, np.float64(0.1666666666666667)),
 (252, np.float64(0.1666666666666667)),
 (253, np.float64(0.1666666666666667)),
 (254, np.float64(0.1666666666666667)),
 (255, np.float64(0.1666666666666667)),
 (256, np.float64(0.1666666666666667)),
 (257, np.float64(0.1666666666666667)),
 (258, np.float64(0.1666666666666667)),
 (259, np.float64(0.1666666666666667)),
 (260, np.float64(0.1666666666666667)),
 (261, np.float64(0.3333333333333334)),
 (262, np.float64(0.14433756729740646)),
 (263, np.float64(0.3333333333333334)),
 (264, np.float64(0.1666666666666667)),
 (265, np.float64(0.1543033499620919)),
 (266, np.float64(0.1543033499620919)),
 (267, np.float64(0.1543033499620919)),
 (268, np.float64(0.3333333333333334)),
 (269, np.float64(0.3333333333333334)),
 (270, np.float64(0.1666666666666667)),
 (271, np.float64(0.1666666666666667)),
 (272, np.float64(0.1543033499620919)),
 (273, np.float64(0.1666666666666667)),
 (274, np.float64(0.3333333333333334)),
 (275, np.float64(0.3333333333333334)),
 (276, np.float64(0.1543033499620919)),
 (277, np.float64(0.1543033499620919)),
 (278, np.float64(0.1666666666666667)),
 (279, np.float64(0.3333333333333334)),
 (280, np.float64(0.3333333333333334)),
 (281, np.float64(0.3333333333333334)),
 (282, np.float64(0.3333333333333334)),
 (283, np.float64(0.1666666666666667)),
 (284, np.float64(0.1666666666666667)),
 (285, np.float64(0.1666666666666667)),
 (286, np.float64(0.1666666666666667)),
 (287, np.float64(0.3333333333333334)),
 (288, np.float64(0.1543033499620919)),
 (289, np.float64(0.3333333333333334)),
 (290, np.float64(0.1543033499620919)),
 (291, np.float64(0.1543033499620919)),
 (292, np.float64(0.1666666666666667)),
 (293, np.float64(0.1666666666666667)),
 (294, np.float64(0.1666666666666667)),
 (295, np.float64(0.3333333333333334)),
 (296, np.float64(0.1666666666666667)),
 (297, np.float64(0.1666666666666667)),
 (298, np.float64(0.1666666666666667)),
 (299, np.float64(0.1666666666666667)),
 (300, np.float64(0.1666666666666667)),
 (301, np.float64(0.3333333333333334)),
 (302, np.float64(0.1666666666666667)),
 (303, np.float64(0.1666666666666667)),
 (304, np.float64(0.1666666666666667)),
 (305, np.float64(0.1666666666666667)),
 (306, np.float64(0.1666666666666667)),
 (307, np.float64(0.1666666666666667)),
 (308, np.float64(0.1666666666666667)),
 (309, np.float64(0.1666666666666667)),
 (310, np.float64(0.1666666666666667)),
 (311, np.float64(0.1666666666666667)),
 (312, np.float64(0.1666666666666667)),
 (313, np.float64(0.1666666666666667)),
 (314, np.float64(0.1666666666666667)),
 (315, np.float64(0.1666666666666667)),
 (316, np.float64(0.1666666666666667)),
 (317, np.float64(0.1666666666666667)),
 (318, np.float64(0.1666666666666667)),
 (319, np.float64(0.1666666666666667)),
 (320, np.float64(0.1666666666666667)),
 (321, np.float64(0.1666666666666667)),
 (322, np.float64(0.1666666666666667)),
 (323, np.float64(0.1666666666666667)),
 (324, np.float64(0.1666666666666667)),
 (325, np.float64(0.1666666666666667)),
 (326, np.float64(0.1543033499620919)),
 (327, np.float64(0.3333333333333334)),
 (328, np.float64(0.1666666666666667)),
 (329, np.float64(0.1666666666666667)),
 (330, np.float64(0.3333333333333334)),
 (331, np.float64(0.1666666666666667)),
 (332, np.float64(0.1666666666666667)),
 (333, np.float64(0.1666666666666667)),
 (334, np.float64(0.1543033499620919)),
 (335, np.float64(0.1666666666666667)),
 (336, np.float64(0.1666666666666667)),
 (337, np.float64(0.1666666666666667)),
 (338, np.float64(0.1666666666666667)),
 (339, np.float64(0.1666666666666667)),
 (340, np.float64(0.1666666666666667)),
 (341, np.float64(0.3333333333333334)),
 (342, np.float64(0.3333333333333334)),
 (343, np.float64(0.1666666666666667)),
 (344, np.float64(0.1666666666666667)),
 (345, np.float64(0.1666666666666667)),
 (346, np.float64(0.1666666666666667)),
 (347, np.float64(0.1666666666666667)),
 (348, np.float64(0.1666666666666667)),
 (349, np.float64(0.1666666666666667)),
 (350, np.float64(0.1666666666666667)),
 (351, np.float64(0.1666666666666667)),
 (352, np.float64(0.1666666666666667)),
 (353, np.float64(0.1666666666666667)),
 (354, np.float64(0.1666666666666667)),
 (355, np.float64(0.1666666666666667)),
 (356, np.float64(0.1666666666666667)),
 (357, np.float64(0.1666666666666667)),
 (358, np.float64(0.1666666666666667)),
 (359, np.float64(0.1666666666666667)),
 (360, np.float64(0.1666666666666667)),
 (361, np.float64(0.1666666666666667)),
 (362, np.float64(0.1666666666666667)),
 (363, np.float64(0.1666666666666667)),
 (364, np.float64(0.1666666666666667)),
 (365, np.float64(0.1666666666666667)),
 (366, np.float64(0.1666666666666667)),
 (367, np.float64(0.1666666666666667)),
 (368, np.float64(0.1666666666666667)),
 (369, np.float64(0.1666666666666667)),
 (370, np.float64(0.1666666666666667)),
 (371, np.float64(0.1666666666666667)),
 (372, np.float64(0.0)),
 (373, np.float64(0.1666666666666667)),
 (374, np.float64(0.1666666666666667)),
 (375, np.float64(0.1666666666666667)),
 (376, np.float64(0.1666666666666667)),
 (377, np.float64(0.1666666666666667)),
 (378, np.float64(0.1543033499620919)),
 (379, np.float64(0.1543033499620919)),
 (380, np.float64(0.1666666666666667)),
 (381, np.float64(0.1666666666666667)),
 (382, np.float64(0.1666666666666667)),
 (383, np.float64(0.1666666666666667)),
 (384, np.float64(0.1666666666666667)),
 (385, np.float64(0.1666666666666667)),
 (386, np.float64(0.1666666666666667)),
 (387, np.float64(0.1666666666666667)),
 (388, np.float64(0.1666666666666667)),
 (389, np.float64(0.1666666666666667)),
 (390, np.float64(0.1666666666666667)),
 (391, np.float64(0.1666666666666667)),
 (392, np.float64(0.1666666666666667)),
 (393, np.float64(0.1666666666666667)),
 (394, np.float64(0.1666666666666667)),
 (395, np.float64(0.1666666666666667)),
 (396, np.float64(0.1666666666666667)),
 (397, np.float64(0.1666666666666667)),
 (398, np.float64(0.1666666666666667)),
 (399, np.float64(0.1666666666666667)),
 (400, np.float64(0.1666666666666667)),
 (401, np.float64(0.1666666666666667)),
 (402, np.float64(0.1666666666666667)),
 (403, np.float64(0.1666666666666667)),
 (404, np.float64(0.1666666666666667)),
 (405, np.float64(0.1666666666666667)),
 (406, np.float64(0.0)),
 (407, np.float64(0.0)),
 (408, np.float64(0.1666666666666667)),
 (409, np.float64(0.0)),
 (410, np.float64(0.1666666666666667)),
 (411, np.float64(0.0)),
 (412, np.float64(0.1543033499620919)),
 (413, np.float64(0.1543033499620919)),
 (414, np.float64(0.1543033499620919)),
 (415, np.float64(0.1543033499620919)),
 (416, np.float64(0.1543033499620919)),
 (417, np.float64(0.1543033499620919)),
 (418, np.float64(0.1543033499620919)),
 (419, np.float64(0.1543033499620919)),
 (420, np.float64(0.1543033499620919)),
 (421, np.float64(0.1543033499620919)),
 (422, np.float64(0.1543033499620919)),
 (423, np.float64(0.1543033499620919)),
 (424, np.float64(0.1543033499620919)),
 (425, np.float64(0.1543033499620919)),
 (426, np.float64(0.1543033499620919)),
 (427, np.float64(0.1543033499620919)),
 (428, np.float64(0.1543033499620919)),
 (429, np.float64(0.1543033499620919)),
 (430, np.float64(0.1543033499620919)),
 (431, np.float64(0.1543033499620919)),
 (432, np.float64(0.1543033499620919)),
 (433, np.float64(0.1543033499620919)),
 (434, np.float64(0.1543033499620919)),
 (435, np.float64(0.1543033499620919)),
 (436, np.float64(0.1543033499620919)),
 (437, np.float64(0.1543033499620919)),
 (438, np.float64(0.1543033499620919)),
 (439, np.float64(0.1543033499620919)),
 (440, np.float64(0.1543033499620919)),
 (441, np.float64(0.1543033499620919)),
 (442, np.float64(0.1543033499620919)),
 (443, np.float64(0.1543033499620919)),
 (444, np.float64(0.1543033499620919)),
 (445, np.float64(0.1543033499620919)),
 (446, np.float64(0.1543033499620919)),
 (447, np.float64(0.1543033499620919)),
 (448, np.float64(0.1543033499620919)),
 (449, np.float64(0.1543033499620919)),
 (450, np.float64(0.1543033499620919)),
 (451, np.float64(0.1543033499620919)),
 (452, np.float64(0.1543033499620919)),
 (453, np.float64(0.1543033499620919)),
 (454, np.float64(0.1666666666666667)),
 (455, np.float64(0.1543033499620919)),
 (456, np.float64(0.1543033499620919)),
 (457, np.float64(0.1543033499620919)),
 (458, np.float64(0.3333333333333334)),
 (459, np.float64(0.1543033499620919)),
 (460, np.float64(0.1543033499620919)),
 (461, np.float64(0.1543033499620919)),
 (462, np.float64(0.1543033499620919)),
 (463, np.float64(0.1543033499620919)),
 (464, np.float64(0.1543033499620919)),
 (465, np.float64(0.1543033499620919)),
 (466, np.float64(0.1543033499620919)),
 (467, np.float64(0.1543033499620919)),
 (468, np.float64(0.1543033499620919)),
 (469, np.float64(0.1543033499620919)),
 (470, np.float64(0.1543033499620919)),
 (471, np.float64(0.1543033499620919)),
 (472, np.float64(0.1543033499620919)),
 (473, np.float64(0.1543033499620919)),
 (474, np.float64(0.1543033499620919)),
 (475, np.float64(0.3333333333333334)),
 (476, np.float64(0.1543033499620919)),
 (477, np.float64(0.1543033499620919)),
 (478, np.float64(0.1543033499620919)),
 (479, np.float64(0.1543033499620919)),
 (480, np.float64(0.1543033499620919)),
 (481, np.float64(0.1543033499620919)),
 (482, np.float64(0.1543033499620919)),
 (483, np.float64(0.1543033499620919)),
 (484, np.float64(0.1543033499620919)),
 (485, np.float64(0.1543033499620919)),
 (486, np.float64(0.1543033499620919)),
 (487, np.float64(0.1543033499620919)),
 (488, np.float64(0.1543033499620919)),
 (489, np.float64(0.1543033499620919)),
 (490, np.float64(0.1543033499620919)),
 (491, np.float64(0.1543033499620919)),
 (492, np.float64(0.1543033499620919)),
 (493, np.float64(0.1543033499620919)),
 (494, np.float64(0.1543033499620919)),
 (495, np.float64(0.1543033499620919)),
 (496, np.float64(0.1543033499620919)),
 (497, np.float64(0.1543033499620919)),
 (498, np.float64(0.1543033499620919)),
 (499, np.float64(0.1543033499620919)),
 (500, np.float64(0.1543033499620919)),
 (501, np.float64(0.1543033499620919)),

- With this, we have synced index number in following variables 'distances, final_df, vector'

In [41]:
# So now we wanted top 10 similar movies
# we will sort, then get 10 similar movies
# Sort function with 'reverse=True' will sort values in descending order on basis of 'index_list'. we use'key= lambda x:x[1]' to achieve this

similar_app = sorted(index_list, reverse=True,key=lambda x: x[1])
similar_app

[(691, np.float64(1.0000000000000002)),
 (693, np.float64(1.0000000000000002)),
 (694, np.float64(1.0000000000000002)),
 (700, np.float64(1.0000000000000002)),
 (701, np.float64(1.0000000000000002)),
 (702, np.float64(1.0000000000000002)),
 (703, np.float64(1.0000000000000002)),
 (705, np.float64(1.0000000000000002)),
 (711, np.float64(1.0000000000000002)),
 (712, np.float64(1.0000000000000002)),
 (714, np.float64(1.0000000000000002)),
 (722, np.float64(1.0000000000000002)),
 (724, np.float64(1.0000000000000002)),
 (725, np.float64(1.0000000000000002)),
 (726, np.float64(1.0000000000000002)),
 (727, np.float64(1.0000000000000002)),
 (730, np.float64(1.0000000000000002)),
 (731, np.float64(1.0000000000000002)),
 (732, np.float64(1.0000000000000002)),
 (734, np.float64(1.0000000000000002)),
 (738, np.float64(1.0000000000000002)),
 (739, np.float64(1.0000000000000002)),
 (740, np.float64(1.0000000000000002)),
 (741, np.float64(1.0000000000000002)),
 (742, np.float64(1.0000000000000002)),
 (743, np.float64(1.0000000000000002)),
 (744, np.float64(1.0000000000000002)),
 (745, np.float64(1.0000000000000002)),
 (746, np.float64(1.0000000000000002)),
 (749, np.float64(1.0000000000000002)),
 (751, np.float64(1.0000000000000002)),
 (752, np.float64(1.0000000000000002)),
 (753, np.float64(1.0000000000000002)),
 (754, np.float64(1.0000000000000002)),
 (755, np.float64(1.0000000000000002)),
 (756, np.float64(1.0000000000000002)),
 (757, np.float64(1.0000000000000002)),
 (758, np.float64(1.0000000000000002)),
 (759, np.float64(1.0000000000000002)),
 (760, np.float64(1.0000000000000002)),
 (762, np.float64(1.0000000000000002)),
 (763, np.float64(1.0000000000000002)),
 (764, np.float64(1.0000000000000002)),
 (765, np.float64(1.0000000000000002)),
 (767, np.float64(1.0000000000000002)),
 (769, np.float64(1.0000000000000002)),
 (770, np.float64(1.0000000000000002)),
 (773, np.float64(1.0000000000000002)),
 (774, np.float64(1.0000000000000002)),
 (775, np.float64(1.0000000000000002)),
 (777, np.float64(1.0000000000000002)),
 (779, np.float64(1.0000000000000002)),
 (781, np.float64(1.0000000000000002)),
 (785, np.float64(1.0000000000000002)),
 (786, np.float64(1.0000000000000002)),
 (787, np.float64(1.0000000000000002)),
 (789, np.float64(1.0000000000000002)),
 (692, np.float64(0.8333333333333336)),
 (696, np.float64(0.8333333333333336)),
 (697, np.float64(0.8333333333333336)),
 (698, np.float64(0.8333333333333336)),
 (699, np.float64(0.8333333333333336)),
 (704, np.float64(0.8333333333333336)),
 (706, np.float64(0.8333333333333336)),
 (707, np.float64(0.8333333333333336)),
 (709, np.float64(0.8333333333333336)),
 (710, np.float64(0.8333333333333336)),
 (713, np.float64(0.8333333333333336)),
 (715, np.float64(0.8333333333333336)),
 (716, np.float64(0.8333333333333336)),
 (718, np.float64(0.8333333333333336)),
 (719, np.float64(0.8333333333333336)),
 (721, np.float64(0.8333333333333336)),
 (728, np.float64(0.8333333333333336)),
 (729, np.float64(0.8333333333333336)),
 (733, np.float64(0.8333333333333336)),
 (735, np.float64(0.8333333333333336)),
 (736, np.float64(0.8333333333333336)),
 (737, np.float64(0.8333333333333336)),
 (748, np.float64(0.8333333333333336)),
 (776, np.float64(0.8333333333333336)),
 (782, np.float64(0.8333333333333336)),
 (783, np.float64(0.8333333333333336)),
 (791, np.float64(0.8333333333333336)),
 (792, np.float64(0.8333333333333336)),
 (3094, np.float64(0.8164965809277261)),
 (3230, np.float64(0.8164965809277261)),
 (3366, np.float64(0.8164965809277261)),
 (3596, np.float64(0.8164965809277261)),
 (3747, np.float64(0.8164965809277261)),
 (3753, np.float64(0.8164965809277261)),
 (3757, np.float64(0.8164965809277261)),
 (3761, np.float64(0.8164965809277261)),
 (3860, np.float64(0.8164965809277261)),
 (4117, np.float64(0.8164965809277261)),
 (4304, np.float64(0.8164965809277261)),
 (4321, np.float64(0.8164965809277261)),
 (4347, np.float64(0.8164965809277261)),
 (4364, np.float64(0.8164965809277261)),
 (4454, np.float64(0.8164965809277261)),
 (4570, np.float64(0.8164965809277261)),
 (4587, np.float64(0.8164965809277261)),
 (4643, np.float64(0.8164965809277261)),
 (4645, np.float64(0.8164965809277261)),
 (4694, np.float64(0.8164965809277261)),
 (4717, np.float64(0.8164965809277261)),
 (4762, np.float64(0.8164965809277261)),
 (4992, np.float64(0.8164965809277261)),
 (5053, np.float64(0.8164965809277261)),
 (5059, np.float64(0.8164965809277261)),
 (5068, np.float64(0.8164965809277261)),
 (5071, np.float64(0.8164965809277261)),
 (5083, np.float64(0.8164965809277261)),
 (5088, np.float64(0.8164965809277261)),
 (5089, np.float64(0.8164965809277261)),
 (5101, np.float64(0.8164965809277261)),
 (5103, np.float64(0.8164965809277261)),
 (5109, np.float64(0.8164965809277261)),
 (5258, np.float64(0.8164965809277261)),
 (5318, np.float64(0.8164965809277261)),
 (5328, np.float64(0.8164965809277261)),
 (5385, np.float64(0.8164965809277261)),
 (5411, np.float64(0.8164965809277261)),
 (5683, np.float64(0.8164965809277261)),
 (5943, np.float64(0.8164965809277261)),
 (6027, np.float64(0.8164965809277261)),
 (6061, np.float64(0.8164965809277261)),
 (6248, np.float64(0.8164965809277261)),
 (6252, np.float64(0.8164965809277261)),
 (6264, np.float64(0.8164965809277261)),
 (6601, np.float64(0.8164965809277261)),
 (6720, np.float64(0.8164965809277261)),
 (6746, np.float64(0.8164965809277261)),
 (6766, np.float64(0.8164965809277261)),
 (6801, np.float64(0.8164965809277261)),
 (6816, np.float64(0.8164965809277261)),
 (6930, np.float64(0.8164965809277261)),
 (6935, np.float64(0.8164965809277261)),
 (6940, np.float64(0.8164965809277261)),
 (6950, np.float64(0.8164965809277261)),
 (6952, np.float64(0.8164965809277261)),
 (6954, np.float64(0.8164965809277261)),
 (7053, np.float64(0.8164965809277261)),
 (7089, np.float64(0.8164965809277261)),
 (7097, np.float64(0.8164965809277261)),
 (7116, np.float64(0.8164965809277261)),
 (7571, np.float64(0.8164965809277261)),
 (7770, np.float64(0.8164965809277261)),
 (8051, np.float64(0.8164965809277261)),
 (8249, np.float64(0.8164965809277261)),
 (8364, np.float64(0.8164965809277261)),
 (8365, np.float64(0.8164965809277261)),
 (8368, np.float64(0.8164965809277261)),
 (8670, np.float64(0.8164965809277261)),
 (8813, np.float64(0.8164965809277261)),
 (8929, np.float64(0.8164965809277261)),
 (9171, np.float64(0.8164965809277261)),
 (9198, np.float64(0.8164965809277261)),
 (9375, np.float64(0.8164965809277261)),
 (9377, np.float64(0.8164965809277261)),
 (9381, np.float64(0.8164965809277261)),
 (9390, np.float64(0.8164965809277261)),
 (9456, np.float64(0.8164965809277261)),
 (9598, np.float64(0.8164965809277261)),
 (9610, np.float64(0.8164965809277261)),
 (708, np.float64(0.7715167498104596)),
 (723, np.float64(0.7715167498104596)),
 (747, np.float64(0.7715167498104596)),
 (761, np.float64(0.7715167498104596)),
 (772, np.float64(0.7715167498104596)),
 (788, np.float64(0.7715167498104596)),
 (695, np.float64(0.7216878364870323)),
 (717, np.float64(0.7216878364870323)),
 (720, np.float64(0.7216878364870323)),
 (766, np.float64(0.7216878364870323)),
 (771, np.float64(0.7216878364870323)),
 (778, np.float64(0.7216878364870323)),
 (780, np.float64(0.7216878364870323)),
 (750, np.float64(0.6804138174397717)),
 (768, np.float64(0.6804138174397717)),
 (784, np.float64(0.6666666666666669)),
 (790, np.float64(0.6172133998483676)),
 (3090, np.float64(0.6123724356957946)),
 (3096, np.float64(0.6123724356957946)),
 (3110, np.float64(0.6123724356957946)),
 (3117, np.float64(0.6123724356957946)),
 (3183, np.float64(0.6123724356957946)),
 (3192, np.float64(0.6123724356957946)),
 (3233, np.float64(0.6123724356957946)),
 (3314, np.float64(0.6123724356957946)),
 (3327, np.float64(0.6123724356957946)),
 (3331, np.float64(0.6123724356957946)),
 (3336, np.float64(0.6123724356957946)),
 (3343, np.float64(0.6123724356957946)),
 (3349, np.float64(0.6123724356957946)),
 (3350, np.float64(0.6123724356957946)),
 (3369, np.float64(0.6123724356957946)),
 (3372, np.float64(0.6123724356957946)),
 (3374, np.float64(0.6123724356957946)),
 (3378, np.float64(0.6123724356957946)),
 (3380, np.float64(0.6123724356957946)),
 (3407, np.float64(0.6123724356957946)),
 (3409, np.float64(0.6123724356957946)),
 (3425, np.float64(0.6123724356957946)),
 (3432, np.float64(0.6123724356957946)),
 (3433, np.float64(0.6123724356957946)),
 (3446, np.float64(0.6123724356957946)),
 (3447, np.float64(0.6123724356957946)),
 (3600, np.float64(0.6123724356957946)),
 (3601, np.float64(0.6123724356957946)),
 (3680, np.float64(0.6123724356957946)),
 (3685, np.float64(0.6123724356957946)),
 (3726, np.float64(0.6123724356957946)),
 (3739, np.float64(0.6123724356957946)),
 (3746, np.float64(0.6123724356957946)),
 (3768, np.float64(0.6123724356957946)),
 (3782, np.float64(0.6123724356957946)),
 (3784, np.float64(0.6123724356957946)),
 (3786, np.float64(0.6123724356957946)),
 (3791, np.float64(0.6123724356957946)),
 (3831, np.float64(0.6123724356957946)),
 (3859, np.float64(0.6123724356957946)),
 (3863, np.float64(0.6123724356957946)),
 (3951, np.float64(0.6123724356957946)),
 (3961, np.float64(0.6123724356957946)),
 (3962, np.float64(0.6123724356957946)),
 (3984, np.float64(0.6123724356957946)),
 (3989, np.float64(0.6123724356957946)),
 (4062, np.float64(0.6123724356957946)),
 (4091, np.float64(0.6123724356957946)),
 (4160, np.float64(0.6123724356957946)),
 (4174, np.float64(0.6123724356957946)),
 (4186, np.float64(0.6123724356957946)),
 (4192, np.float64(0.6123724356957946)),
 (4198, np.float64(0.6123724356957946)),
 (4202, np.float64(0.6123724356957946)),
 (4212, np.float64(0.6123724356957946)),
 (4223, np.float64(0.6123724356957946)),
 (4225, np.float64(0.6123724356957946)),
 (4226, np.float64(0.6123724356957946)),
 (4239, np.float64(0.6123724356957946)),
 (4242, np.float64(0.6123724356957946)),
 (4254, np.float64(0.6123724356957946)),
 (4261, np.float64(0.6123724356957946)),
 (4308, np.float64(0.6123724356957946)),
 (4312, np.float64(0.6123724356957946)),
 (4314, np.float64(0.6123724356957946)),
 (4318, np.float64(0.6123724356957946)),
 (4338, np.float64(0.6123724356957946)),
 (4341, np.float64(0.6123724356957946)),
 (4527, np.float64(0.6123724356957946)),
 (4567, np.float64(0.6123724356957946)),
 (4569, np.float64(0.6123724356957946)),
 (4580, np.float64(0.6123724356957946)),
 (4583, np.float64(0.6123724356957946)),
 (4584, np.float64(0.6123724356957946)),
 (4618, np.float64(0.6123724356957946)),
 (4624, np.float64(0.6123724356957946)),
 (4638, np.float64(0.6123724356957946)),
 (4687, np.float64(0.6123724356957946)),
 (4690, np.float64(0.6123724356957946)),
 (4707, np.float64(0.6123724356957946)),
 (4721, np.float64(0.6123724356957946)),
 (4774, np.float64(0.6123724356957946)),
 (4784, np.float64(0.6123724356957946)),
 (4834, np.float64(0.6123724356957946)),
 (4847, np.float64(0.6123724356957946)),
 (4873, np.float64(0.6123724356957946)),
 (4889, np.float64(0.6123724356957946)),
 (4897, np.float64(0.6123724356957946)),
 (4906, np.float64(0.6123724356957946)),
 (4922, np.float64(0.6123724356957946)),
 (4933, np.float64(0.6123724356957946)),
 (4935, np.float64(0.6123724356957946)),
 (4961, np.float64(0.6123724356957946)),
 (4996, np.float64(0.6123724356957946)),
 (4999, np.float64(0.6123724356957946)),
 (5002, np.float64(0.6123724356957946)),
 (5006, np.float64(0.6123724356957946)),
 (5010, np.float64(0.6123724356957946)),
 (5018, np.float64(0.6123724356957946)),
 (5025, np.float64(0.6123724356957946)),
 (5032, np.float64(0.6123724356957946)),
 (5061, np.float64(0.6123724356957946)),
 (5079, np.float64(0.6123724356957946)),
 (5094, np.float64(0.6123724356957946)),
 (5105, np.float64(0.6123724356957946)),
 (5112, np.float64(0.6123724356957946)),
 (5116, np.float64(0.6123724356957946)),
 (5128, np.float64(0.6123724356957946)),
 (5134, np.float64(0.6123724356957946)),
 (5140, np.float64(0.6123724356957946)),
 (5142, np.float64(0.6123724356957946)),
 (5143, np.float64(0.6123724356957946)),
 (5157, np.float64(0.6123724356957946)),
 (5165, np.float64(0.6123724356957946)),
 (5183, np.float64(0.6123724356957946)),
 (5217, np.float64(0.6123724356957946)),
 (5225, np.float64(0.6123724356957946)),
 (5294, np.float64(0.6123724356957946)),
 (5305, np.float64(0.6123724356957946)),
 (5306, np.float64(0.6123724356957946)),
 (5325, np.float64(0.6123724356957946)),
 (5330, np.float64(0.6123724356957946)),
 (5345, np.float64(0.6123724356957946)),
 (5365, np.float64(0.6123724356957946)),
 (5369, np.float64(0.6123724356957946)),
 (5371, np.float64(0.6123724356957946)),
 (5378, np.float64(0.6123724356957946)),
 (5460, np.float64(0.6123724356957946)),
 (5475, np.float64(0.6123724356957946)),
 (5559, np.float64(0.6123724356957946)),
 (5579, np.float64(0.6123724356957946)),
 (5638, np.float64(0.6123724356957946)),
 (5644, np.float64(0.6123724356957946)),
 (5651, np.float64(0.6123724356957946)),
 (5652, np.float64(0.6123724356957946)),
 (5658, np.float64(0.6123724356957946)),
 (5686, np.float64(0.6123724356957946)),
 (5688, np.float64(0.6123724356957946)),
 (5814, np.float64(0.6123724356957946)),
 (5938, np.float64(0.6123724356957946)),
 (5939, np.float64(0.6123724356957946)),
 (5941, np.float64(0.6123724356957946)),
 (5945, np.float64(0.6123724356957946)),
 (5947, np.float64(0.6123724356957946)),
 (5949, np.float64(0.6123724356957946)),
 (5951, np.float64(0.6123724356957946)),
 (5952, np.float64(0.6123724356957946)),
 (5953, np.float64(0.6123724356957946)),
 (5954, np.float64(0.6123724356957946)),
 (5959, np.float64(0.6123724356957946)),
 (5962, np.float64(0.6123724356957946)),
 (5965, np.float64(0.6123724356957946)),
 (5966, np.float64(0.6123724356957946)),
 (5968, np.float64(0.6123724356957946)),
 (5972, np.float64(0.6123724356957946)),
 (5973, np.float64(0.6123724356957946)),
 (5981, np.float64(0.6123724356957946)),
 (6001, np.float64(0.6123724356957946)),
 (6020, np.float64(0.6123724356957946)),
 (6079, np.float64(0.6123724356957946)),
 (6104, np.float64(0.6123724356957946)),
 (6110, np.float64(0.6123724356957946)),
 (6160, np.float64(0.6123724356957946)),
 (6238, np.float64(0.6123724356957946)),
 (6240, np.float64(0.6123724356957946)),
 (6246, np.float64(0.6123724356957946)),
 (6251, np.float64(0.6123724356957946)),
 (6258, np.float64(0.6123724356957946)),
 (6261, np.float64(0.6123724356957946)),
 (6266, np.float64(0.6123724356957946)),
 (6315, np.float64(0.6123724356957946)),
 (6333, np.float64(0.6123724356957946)),
 (6344, np.float64(0.6123724356957946)),
 (6349, np.float64(0.6123724356957946)),
 (6375, np.float64(0.6123724356957946)),
 (6393, np.float64(0.6123724356957946)),
 (6414, np.float64(0.6123724356957946)),
 (6515, np.float64(0.6123724356957946)),
 (6548, np.float64(0.6123724356957946)),
 (6549, np.float64(0.6123724356957946)),
 (6600, np.float64(0.6123724356957946)),
 (6613, np.float64(0.6123724356957946)),
 (6617, np.float64(0.6123724356957946)),
 (6628, np.float64(0.6123724356957946)),
 (6630, np.float64(0.6123724356957946)),
 (6632, np.float64(0.6123724356957946)),
 (6691, np.float64(0.6123724356957946)),
 (6694, np.float64(0.6123724356957946)),
 (6695, np.float64(0.6123724356957946)),
 (6701, np.float64(0.6123724356957946)),
 (6703, np.float64(0.6123724356957946)),
 (6708, np.float64(0.6123724356957946)),
 (6709, np.float64(0.6123724356957946)),
 (6710, np.float64(0.6123724356957946)),
 (6719, np.float64(0.6123724356957946)),
 (6721, np.float64(0.6123724356957946)),
 (6750, np.float64(0.6123724356957946)),
 (6773, np.float64(0.6123724356957946)),
 (6774, np.float64(0.6123724356957946)),
 (6778, np.float64(0.6123724356957946)),
 (6814, np.float64(0.6123724356957946)),
 (6909, np.float64(0.6123724356957946)),
 (6911, np.float64(0.6123724356957946)),
 (6927, np.float64(0.6123724356957946)),
 (6946, np.float64(0.6123724356957946)),
 (6957, np.float64(0.6123724356957946)),
 (6958, np.float64(0.6123724356957946)),
 (6959, np.float64(0.6123724356957946)),
 (6962, np.float64(0.6123724356957946)),
 (6963, np.float64(0.6123724356957946)),
 (6978, np.float64(0.6123724356957946)),
 (6990, np.float64(0.6123724356957946)),
 (6994, np.float64(0.6123724356957946)),
 (7016, np.float64(0.6123724356957946)),
 (7023, np.float64(0.6123724356957946)),
 (7079, np.float64(0.6123724356957946)),
 (7169, np.float64(0.6123724356957946)),
 (7182, np.float64(0.6123724356957946)),
 (7186, np.float64(0.6123724356957946)),
 (7202, np.float64(0.6123724356957946)),
 (7233, np.float64(0.6123724356957946)),
 (7241, np.float64(0.6123724356957946)),
 (7271, np.float64(0.6123724356957946)),
 (7301, np.float64(0.6123724356957946)),
 (7310, np.float64(0.6123724356957946)),
 (7312, np.float64(0.6123724356957946)),
 (7355, np.float64(0.6123724356957946)),
 (7358, np.float64(0.6123724356957946)),
 (7380, np.float64(0.6123724356957946)),
 (7383, np.float64(0.6123724356957946)),
 (7392, np.float64(0.6123724356957946)),
 (7409, np.float64(0.6123724356957946)),
 (7414, np.float64(0.6123724356957946)),
 (7504, np.float64(0.6123724356957946)),
 (7508, np.float64(0.6123724356957946)),
 (7512, np.float64(0.6123724356957946)),
 (7546, np.float64(0.6123724356957946)),
 (7550, np.float64(0.6123724356957946)),
 (7554, np.float64(0.6123724356957946)),
 (7560, np.float64(0.6123724356957946)),
 (7564, np.float64(0.6123724356957946)),
 (7570, np.float64(0.6123724356957946)),
 (7572, np.float64(0.6123724356957946)),
 (7573, np.float64(0.6123724356957946)),
 (7581, np.float64(0.6123724356957946)),
 (7582, np.float64(0.6123724356957946)),
 (7584, np.float64(0.6123724356957946)),
 (7585, np.float64(0.6123724356957946)),
 (7614, np.float64(0.6123724356957946)),
 (7656, np.float64(0.6123724356957946)),
 (7720, np.float64(0.6123724356957946)),
 (7727, np.float64(0.6123724356957946)),
 (7731, np.float64(0.6123724356957946)),
 (7785, np.float64(0.6123724356957946)),
 (7788, np.float64(0.6123724356957946)),
 (7792, np.float64(0.6123724356957946)),
 (7799, np.float64(0.6123724356957946)),
 (7801, np.float64(0.6123724356957946)),
 (7817, np.float64(0.6123724356957946)),
 (7820, np.float64(0.6123724356957946)),
 (7825, np.float64(0.6123724356957946)),
 (7942, np.float64(0.6123724356957946)),
 (7987, np.float64(0.6123724356957946)),
 (8001, np.float64(0.6123724356957946)),
 (8061, np.float64(0.6123724356957946)),
 (8101, np.float64(0.6123724356957946)),
 (8115, np.float64(0.6123724356957946)),
 (8163, np.float64(0.6123724356957946)),
 (8182, np.float64(0.6123724356957946)),
 (8217, np.float64(0.6123724356957946)),
 (8220, np.float64(0.6123724356957946)),
 (8299, np.float64(0.6123724356957946)),
 (8338, np.float64(0.6123724356957946)),
 (8342, np.float64(0.6123724356957946)),
 (8348, np.float64(0.6123724356957946)),
 (8355, np.float64(0.6123724356957946)),
 (8359, np.float64(0.6123724356957946)),
 (8363, np.float64(0.6123724356957946)),
 (8366, np.float64(0.6123724356957946)),
 (8376, np.float64(0.6123724356957946)),
 (8377, np.float64(0.6123724356957946)),
 (8381, np.float64(0.6123724356957946)),
 (8382, np.float64(0.6123724356957946)),
 (8383, np.float64(0.6123724356957946)),
 (8384, np.float64(0.6123724356957946)),
 (8385, np.float64(0.6123724356957946)),
 (8390, np.float64(0.6123724356957946)),
 (8406, np.float64(0.6123724356957946)),
 (8408, np.float64(0.6123724356957946)),
 (8532, np.float64(0.6123724356957946)),
 (8543, np.float64(0.6123724356957946)),
 (8552, np.float64(0.6123724356957946)),
 (8578, np.float64(0.6123724356957946)),
 (8617, np.float64(0.6123724356957946)),
 (8649, np.float64(0.6123724356957946)),
 (8659, np.float64(0.6123724356957946)),
 (8686, np.float64(0.6123724356957946)),
 (8708, np.float64(0.6123724356957946)),
 (8798, np.float64(0.6123724356957946)),
 (8804, np.float64(0.6123724356957946)),
 (8836, np.float64(0.6123724356957946)),
 (8852, np.float64(0.6123724356957946)),
 (8914, np.float64(0.6123724356957946)),
 (8991, np.float64(0.6123724356957946)),
 (8995, np.float64(0.6123724356957946)),
 (8998, np.float64(0.6123724356957946)),
 (9014, np.float64(0.6123724356957946)),
 (9018, np.float64(0.6123724356957946)),

In [42]:
final_df.loc[691]

App                           netflix
tags    entertain free teen entertain
Name: 691, dtype: object

In [43]:
for i in similar_app:
    print(i)

(691, np.float64(1.0000000000000002))
(693, np.float64(1.0000000000000002))
(694, np.float64(1.0000000000000002))
(700, np.float64(1.0000000000000002))
(701, np.float64(1.0000000000000002))
(702, np.float64(1.0000000000000002))
(703, np.float64(1.0000000000000002))
(705, np.float64(1.0000000000000002))
(711, np.float64(1.0000000000000002))
(712, np.float64(1.0000000000000002))
(714, np.float64(1.0000000000000002))
(722, np.float64(1.0000000000000002))
(724, np.float64(1.0000000000000002))
(725, np.float64(1.0000000000000002))
(726, np.float64(1.0000000000000002))
(727, np.float64(1.0000000000000002))
(730, np.float64(1.0000000000000002))
(731, np.float64(1.0000000000000002))
(732, np.float64(1.0000000000000002))
(734, np.float64(1.0000000000000002))
(738, np.float64(1.0000000000000002))
(739, np.float64(1.0000000000000002))
(740, np.float64(1.0000000000000002))
(741, np.float64(1.0000000000000002))
(742, np.float64(1.0000000000000002))
(743, np.float64(1.0000000000000002))
(744, np.float64(1.0000000000000002))
(745, np.float64(1.0000000000000002))
(746, np.float64(1.0000000000000002))
(749, np.float64(1.0000000000000002))
(751, np.float64(1.0000000000000002))
(752, np.float64(1.0000000000000002))
(753, np.float64(1.0000000000000002))
(754, np.float64(1.0000000000000002))
(755, np.float64(1.0000000000000002))
(756, np.float64(1.0000000000000002))
(757, np.float64(1.0000000000000002))
(758, np.float64(1.0000000000000002))
(759, np.float64(1.0000000000000002))
(760, np.float64(1.0000000000000002))
(762, np.float64(1.0000000000000002))
(763, np.float64(1.0000000000000002))
(764, np.float64(1.0000000000000002))
(765, np.float64(1.0000000000000002))
(767, np.float64(1.0000000000000002))
(769, np.float64(1.0000000000000002))
(770, np.float64(1.0000000000000002))
(773, np.float64(1.0000000000000002))
(774, np.float64(1.0000000000000002))
(775, np.float64(1.0000000000000002))
(777, np.float64(1.0000000000000002))
(779, np.float64(1.0000000000000002))
(781, np.float64(1.0000000000000002))
(785, np.float64(1.0000000000000002))
(786, np.float64(1.0000000000000002))
(787, np.float64(1.0000000000000002))
(789, np.float64(1.0000000000000002))
(692, np.float64(0.8333333333333336))
(696, np.float64(0.8333333333333336))
(697, np.float64(0.8333333333333336))
(698, np.float64(0.8333333333333336))
(699, np.float64(0.8333333333333336))
(704, np.float64(0.8333333333333336))
(706, np.float64(0.8333333333333336))
(707, np.float64(0.8333333333333336))
(709, np.float64(0.8333333333333336))
(710, np.float64(0.8333333333333336))
(713, np.float64(0.8333333333333336))
(715, np.float64(0.8333333333333336))
(716, np.float64(0.8333333333333336))
(718, np.float64(0.8333333333333336))
(719, np.float64(0.8333333333333336))
(721, np.float64(0.8333333333333336))
(728, np.float64(0.8333333333333336))
(729, np.float64(0.8333333333333336))
(733, np.float64(0.8333333333333336))
(735, np.float64(0.8333333333333336))
(736, np.float64(0.8333333333333336))
(737, np.float64(0.8333333333333336))
(748, np.float64(0.8333333333333336))
(776, np.float64(0.8333333333333336))
(782, np.float64(0.8333333333333336))
(783, np.float64(0.8333333333333336))
(791, np.float64(0.8333333333333336))
(792, np.float64(0.8333333333333336))
(3094, np.float64(0.8164965809277261))
(3230, np.float64(0.8164965809277261))
(3366, np.float64(0.8164965809277261))
(3596, np.float64(0.8164965809277261))
(3747, np.float64(0.8164965809277261))
(3753, np.float64(0.8164965809277261))
(3757, np.float64(0.8164965809277261))
(3761, np.float64(0.8164965809277261))
(3860, np.float64(0.8164965809277261))
(4117, np.float64(0.8164965809277261))
(4304, np.float64(0.8164965809277261))
(4321, np.float64(0.8164965809277261))
(4347, np.float64(0.8164965809277261))
(4364, np.float64(0.8164965809277261))
(4454, np.float64(0.8164965809277261))
(4570, np.float64(0.8164965809277261))
(4587, np.float64(0.8164965809277261))
(4643, np.float64(0.8164965809277261))
(4645, np.float64(0.8164965809277261))
(4694, np.float64(0.8164965809277261))
(4717, np.float64(0.8164965809277261))
(4762, np.float64(0.8164965809277261))
(4992, np.float64(0.8164965809277261))
(5053, np.float64(0.8164965809277261))
(5059, np.float64(0.8164965809277261))
(5068, np.float64(0.8164965809277261))
(5071, np.float64(0.8164965809277261))
(5083, np.float64(0.8164965809277261))
(5088, np.float64(0.8164965809277261))
(5089, np.float64(0.8164965809277261))
(5101, np.float64(0.8164965809277261))
(5103, np.float64(0.8164965809277261))
(5109, np.float64(0.8164965809277261))
(5258, np.float64(0.8164965809277261))
(5318, np.float64(0.8164965809277261))
(5328, np.float64(0.8164965809277261))
(5385, np.float64(0.8164965809277261))
(5411, np.float64(0.8164965809277261))
(5683, np.float64(0.8164965809277261))
(5943, np.float64(0.8164965809277261))
(6027, np.float64(0.8164965809277261))
(6061, np.float64(0.8164965809277261))
(6248, np.float64(0.8164965809277261))
(6252, np.float64(0.8164965809277261))
(6264, np.float64(0.8164965809277261))
(6601, np.float64(0.8164965809277261))
(6720, np.float64(0.8164965809277261))
(6746, np.float64(0.8164965809277261))
(6766, np.float64(0.8164965809277261))
(6801, np.float64(0.8164965809277261))
(6816, np.float64(0.8164965809277261))
(6930, np.float64(0.8164965809277261))
(6935, np.float64(0.8164965809277261))
(6940, np.float64(0.8164965809277261))
(6950, np.float64(0.8164965809277261))
(6952, np.float64(0.8164965809277261))
(6954, np.float64(0.8164965809277261))
(7053, np.float64(0.8164965809277261))
(7089, np.float64(0.8164965809277261))
(7097, np.float64(0.8164965809277261))
(7116, np.float64(0.8164965809277261))
(7571, np.float64(0.8164965809277261))
(7770, np.float64(0.8164965809277261))
(8051, np.float64(0.8164965809277261))
(8249, np.float64(0.8164965809277261))
(8364, np.float64(0.8164965809277261))
(8365, np.float64(0.8164965809277261))
(8368, np.float64(0.8164965809277261))
(8670, np.float64(0.8164965809277261))
(8813, np.float64(0.8164965809277261))
(8929, np.float64(0.8164965809277261))
(9171, np.float64(0.8164965809277261))
(9198, np.float64(0.8164965809277261))
(9375, np.float64(0.8164965809277261))
(9377, np.float64(0.8164965809277261))
(9381, np.float64(0.8164965809277261))
(9390, np.float64(0.8164965809277261))
(9456, np.float64(0.8164965809277261))
(9598, np.float64(0.8164965809277261))
(9610, np.float64(0.8164965809277261))
(708, np.float64(0.7715167498104596))
(723, np.float64(0.7715167498104596))
(747, np.float64(0.7715167498104596))
(761, np.float64(0.7715167498104596))
(772, np.float64(0.7715167498104596))
(788, np.float64(0.7715167498104596))
(695, np.float64(0.7216878364870323))
(717, np.float64(0.7216878364870323))
(720, np.float64(0.7216878364870323))
(766, np.float64(0.7216878364870323))
(771, np.float64(0.7216878364870323))
(778, np.float64(0.7216878364870323))
(780, np.float64(0.7216878364870323))
(750, np.float64(0.6804138174397717))
(768, np.float64(0.6804138174397717))
(784, np.float64(0.6666666666666669))
(790, np.float64(0.6172133998483676))
(3090, np.float64(0.6123724356957946))
(3096, np.float64(0.6123724356957946))
(3110, np.float64(0.6123724356957946))
(3117, np.float64(0.6123724356957946))
(3183, np.float64(0.6123724356957946))
(3192, np.float64(0.6123724356957946))
(3233, np.float64(0.6123724356957946))
(3314, np.float64(0.6123724356957946))
(3327, np.float64(0.6123724356957946))
(3331, np.float64(0.6123724356957946))
(3336, np.float64(0.6123724356957946))
(3343, np.float64(0.6123724356957946))
(3349, np.float64(0.6123724356957946))
(3350, np.float64(0.6123724356957946))
(3369, np.float64(0.6123724356957946))
(3372, np.float64(0.6123724356957946))
(3374, np.float64(0.6123724356957946))
(3378, np.float64(0.6123724356957946))
(3380, np.float64(0.6123724356957946))
(3407, np.float64(0.6123724356957946))
(3409, np.float64(0.6123724356957946))
(3425, np.float64(0.6123724356957946))
(3432, np.float64(0.6123724356957946))
(3433, np.float64(0.6123724356957946))
(3446, np.float64(0.6123724356957946))
(3447, np.float64(0.6123724356957946))
(3600, np.float64(0.6123724356957946))
(3601, np.float64(0.6123724356957946))
(3680, np.float64(0.6123724356957946))
(3685, np.float64(0.6123724356957946))
(3726, np.float64(0.6123724356957946))
(3739, np.float64(0.6123724356957946))
(3746, np.float64(0.6123724356957946))
(3768, np.float64(0.6123724356957946))
(3782, np.float64(0.6123724356957946))
(3784, np.float64(0.6123724356957946))
(3786, np.float64(0.6123724356957946))
(3791, np.float64(0.6123724356957946))
(3831, np.float64(0.6123724356957946))
(3859, np.float64(0.6123724356957946))
(3863, np.float64(0.6123724356957946))
(3951, np.float64(0.6123724356957946))
(3961, np.float64(0.6123724356957946))
(3962, np.float64(0.6123724356957946))
(3984, np.float64(0.6123724356957946))
(3989, np.float64(0.6123724356957946))
(4062, np.float64(0.6123724356957946))
(4091, np.float64(0.6123724356957946))
(4160, np.float64(0.6123724356957946))
(4174, np.float64(0.6123724356957946))
(4186, np.float64(0.6123724356957946))
(4192, np.float64(0.6123724356957946))
(4198, np.float64(0.6123724356957946))
(4202, np.float64(0.6123724356957946))
(4212, np.float64(0.6123724356957946))
(4223, np.float64(0.6123724356957946))
(4225, np.float64(0.6123724356957946))
(4226, np.float64(0.6123724356957946))
(4239, np.float64(0.6123724356957946))
(4242, np.float64(0.6123724356957946))
(4254, np.float64(0.6123724356957946))
(4261, np.float64(0.6123724356957946))
(4308, np.float64(0.6123724356957946))
(4312, np.float64(0.6123724356957946))
(4314, np.float64(0.6123724356957946))
(4318, np.float64(0.6123724356957946))
(4338, np.float64(0.6123724356957946))
(4341, np.float64(0.6123724356957946))
(4527, np.float64(0.6123724356957946))
(4567, np.float64(0.6123724356957946))
(4569, np.float64(0.6123724356957946))
(4580, np.float64(0.6123724356957946))
(4583, np.float64(0.6123724356957946))
(4584, np.float64(0.6123724356957946))
(4618, np.float64(0.6123724356957946))
(4624, np.float64(0.6123724356957946))
(4638, np.float64(0.6123724356957946))
(4687, np.float64(0.6123724356957946))
(4690, np.float64(0.6123724356957946))
(4707, np.float64(0.6123724356957946))
(4721, np.float64(0.6123724356957946))
(4774, np.float64(0.6123724356957946))
(4784, np.float64(0.6123724356957946))
(4834, np.float64(0.6123724356957946))
(4847, np.float64(0.6123724356957946))
(4873, np.float64(0.6123724356957946))
(4889, np.float64(0.6123724356957946))
(4897, np.float64(0.6123724356957946))
(4906, np.float64(0.6123724356957946))
(4922, np.float64(0.6123724356957946))
(4933, np.float64(0.6123724356957946))
(4935, np.float64(0.6123724356957946))
(4961, np.float64(0.6123724356957946))
(4996, np.float64(0.6123724356957946))
(4999, np.float64(0.6123724356957946))
(5002, np.float64(0.6123724356957946))
(5006, np.float64(0.6123724356957946))
(5010, np.float64(0.6123724356957946))
(5018, np.float64(0.6123724356957946))
(5025, np.float64(0.6123724356957946))
(5032, np.float64(0.6123724356957946))
(5061, np.float64(0.6123724356957946))
(5079, np.float64(0.6123724356957946))
(5094, np.float64(0.6123724356957946))
(5105, np.float64(0.6123724356957946))
(5112, np.float64(0.6123724356957946))
(5116, np.float64(0.6123724356957946))
(5128, np.float64(0.6123724356957946))
(5134, np.float64(0.6123724356957946))
(5140, np.float64(0.6123724356957946))
(5142, np.float64(0.6123724356957946))
(5143, np.float64(0.6123724356957946))
(5157, np.float64(0.6123724356957946))
(5165, np.float64(0.6123724356957946))
(5183, np.float64(0.6123724356957946))
(5217, np.float64(0.6123724356957946))
(5225, np.float64(0.6123724356957946))
(5294, np.float64(0.6123724356957946))
(5305, np.float64(0.6123724356957946))
(5306, np.float64(0.6123724356957946))
(5325, np.float64(0.6123724356957946))
(5330, np.float64(0.6123724356957946))
(5345, np.float64(0.6123724356957946))
(5365, np.float64(0.6123724356957946))
(5369, np.float64(0.6123724356957946))
(5371, np.float64(0.6123724356957946))
(5378, np.float64(0.6123724356957946))
(5460, np.float64(0.6123724356957946))
(5475, np.float64(0.6123724356957946))
(5559, np.float64(0.6123724356957946))
(5579, np.float64(0.6123724356957946))
(5638, np.float64(0.6123724356957946))
(5644, np.float64(0.6123724356957946))
(5651, np.float64(0.6123724356957946))
(5652, np.float64(0.6123724356957946))
(5658, np.float64(0.6123724356957946))
(5686, np.float64(0.6123724356957946))
(5688, np.float64(0.6123724356957946))
(5814, np.float64(0.6123724356957946))
(5938, np.float64(0.6123724356957946))
(5939, np.float64(0.6123724356957946))
(5941, np.float64(0.6123724356957946))
(5945, np.float64(0.6123724356957946))
(5947, np.float64(0.6123724356957946))
(5949, np.float64(0.6123724356957946))
(5951, np.float64(0.6123724356957946))
(5952, np.float64(0.6123724356957946))
(5953, np.float64(0.6123724356957946))
(5954, np.float64(0.6123724356957946))
(5959, np.float64(0.6123724356957946))
(5962, np.float64(0.6123724356957946))
(5965, np.float64(0.6123724356957946))
(5966, np.float64(0.6123724356957946))
(5968, np.float64(0.6123724356957946))
(5972, np.float64(0.6123724356957946))
(5973, np.float64(0.6123724356957946))
(5981, np.float64(0.6123724356957946))
(6001, np.float64(0.6123724356957946))
(6020, np.float64(0.6123724356957946))
(6079, np.float64(0.6123724356957946))
(6104, np.float64(0.6123724356957946))
(6110, np.float64(0.6123724356957946))
(6160, np.float64(0.6123724356957946))
(6238, np.float64(0.6123724356957946))
(6240, np.float64(0.6123724356957946))
(6246, np.float64(0.6123724356957946))
(6251, np.float64(0.6123724356957946))
(6258, np.float64(0.6123724356957946))
(6261, np.float64(0.6123724356957946))
(6266, np.float64(0.6123724356957946))
(6315, np.float64(0.6123724356957946))
(6333, np.float64(0.6123724356957946))
(6344, np.float64(0.6123724356957946))
(6349, np.float64(0.6123724356957946))
(6375, np.float64(0.6123724356957946))
(6393, np.float64(0.6123724356957946))
(6414, np.float64(0.6123724356957946))
(6515, np.float64(0.6123724356957946))
(6548, np.float64(0.6123724356957946))
(6549, np.float64(0.6123724356957946))
(6600, np.float64(0.6123724356957946))
(6613, np.float64(0.6123724356957946))
(6617, np.float64(0.6123724356957946))
(6628, np.float64(0.6123724356957946))
(6630, np.float64(0.6123724356957946))
(6632, np.float64(0.6123724356957946))
(6691, np.float64(0.6123724356957946))
(6694, np.float64(0.6123724356957946))
(6695, np.float64(0.6123724356957946))
(6701, np.float64(0.6123724356957946))
(6703, np.float64(0.6123724356957946))
(6708, np.float64(0.6123724356957946))
(6709, np.float64(0.6123724356957946))
(6710, np.float64(0.6123724356957946))
(6719, np.float64(0.6123724356957946))
(6721, np.float64(0.6123724356957946))
(6750, np.float64(0.6123724356957946))
(6773, np.float64(0.6123724356957946))
(6774, np.float64(0.6123724356957946))
(6778, np.float64(0.6123724356957946))
(6814, np.float64(0.6123724356957946))
(6909, np.float64(0.6123724356957946))
(6911, np.float64(0.6123724356957946))
(6927, np.float64(0.6123724356957946))
(6946, np.float64(0.6123724356957946))
(6957, np.float64(0.6123724356957946))
(6958, np.float64(0.6123724356957946))
(6959, np.float64(0.6123724356957946))
(6962, np.float64(0.6123724356957946))
(6963, np.float64(0.6123724356957946))
(6978, np.float64(0.6123724356957946))
(6990, np.float64(0.6123724356957946))
(6994, np.float64(0.6123724356957946))
(7016, np.float64(0.6123724356957946))
(7023, np.float64(0.6123724356957946))
(7079, np.float64(0.6123724356957946))
(7169, np.float64(0.6123724356957946))
(7182, np.float64(0.6123724356957946))
(7186, np.float64(0.6123724356957946))
(7202, np.float64(0.6123724356957946))
(7233, np.float64(0.6123724356957946))
(7241, np.float64(0.6123724356957946))
(7271, np.float64(0.6123724356957946))
(7301, np.float64(0.6123724356957946))
(7310, np.float64(0.6123724356957946))
(7312, np.float64(0.6123724356957946))
(7355, np.float64(0.6123724356957946))
(7358, np.float64(0.6123724356957946))
(7380, np.float64(0.6123724356957946))
(7383, np.float64(0.6123724356957946))
(7392, np.float64(0.6123724356957946))
(7409, np.float64(0.6123724356957946))
(7414, np.float64(0.6123724356957946))
(7504, np.float64(0.6123724356957946))
(7508, np.float64(0.6123724356957946))
(7512, np.float64(0.6123724356957946))
(7546, np.float64(0.6123724356957946))
(7550, np.float64(0.6123724356957946))
(7554, np.float64(0.6123724356957946))
(7560, np.float64(0.6123724356957946))
(7564, np.float64(0.6123724356957946))
(7570, np.float64(0.6123724356957946))
(7572, np.float64(0.6123724356957946))
(7573, np.float64(0.6123724356957946))
(7581, np.float64(0.6123724356957946))
(7582, np.float64(0.6123724356957946))
(7584, np.float64(0.6123724356957946))
(7585, np.float64(0.6123724356957946))
(7614, np.float64(0.6123724356957946))
(7656, np.float64(0.6123724356957946))
(7720, np.float64(0.6123724356957946))
(7727, np.float64(0.6123724356957946))
(7731, np.float64(0.6123724356957946))
(7785, np.float64(0.6123724356957946))
(7788, np.float64(0.6123724356957946))
(7792, np.float64(0.6123724356957946))
(7799, np.float64(0.6123724356957946))
(7801, np.float64(0.6123724356957946))
(7817, np.float64(0.6123724356957946))
(7820, np.float64(0.6123724356957946))
(7825, np.float64(0.6123724356957946))
(7942, np.float64(0.6123724356957946))
(7987, np.float64(0.6123724356957946))
(8001, np.float64(0.6123724356957946))
(8061, np.float64(0.6123724356957946))
(8101, np.float64(0.6123724356957946))
(8115, np.float64(0.6123724356957946))
(8163, np.float64(0.6123724356957946))
(8182, np.float64(0.6123724356957946))
(8217, np.float64(0.6123724356957946))
(8220, np.float64(0.6123724356957946))
(8299, np.float64(0.6123724356957946))
(8338, np.float64(0.6123724356957946))
(8342, np.float64(0.6123724356957946))
(8348, np.float64(0.6123724356957946))
(8355, np.float64(0.6123724356957946))
(8359, np.float64(0.6123724356957946))
(8363, np.float64(0.6123724356957946))
(8366, np.float64(0.6123724356957946))
(8376, np.float64(0.6123724356957946))
(8377, np.float64(0.6123724356957946))
(8381, np.float64(0.6123724356957946))
(8382, np.float64(0.6123724356957946))
(8383, np.float64(0.6123724356957946))
(8384, np.float64(0.6123724356957946))
(8385, np.float64(0.6123724356957946))
(8390, np.float64(0.6123724356957946))
(8406, np.float64(0.6123724356957946))
(8408, np.float64(0.6123724356957946))
(8532, np.float64(0.6123724356957946))
(8543, np.float64(0.6123724356957946))
(8552, np.float64(0.6123724356957946))
(8578, np.float64(0.6123724356957946))
(8617, np.float64(0.6123724356957946))
(8649, np.float64(0.6123724356957946))
(8659, np.float64(0.6123724356957946))
(8686, np.float64(0.6123724356957946))
(8708, np.float64(0.6123724356957946))
(8798, np.float64(0.6123724356957946))
(8804, np.float64(0.6123724356957946))
(8836, np.float64(0.6123724356957946))
(8852, np.float64(0.6123724356957946))
(8914, np.float64(0.6123724356957946))
(8991, np.float64(0.6123724356957946))
(8995, np.float64(0.6123724356957946))
(8998, np.float64(0.6123724356957946))
(9014, np.float64(0.6123724356957946))
(9018, np.float64(0.6123724356957946))
(9092, np.float64(0.6123724356957946))
(9093, np.float64(0.6123724356957946))
(9095, np.float64(0.6123724356957946))
(9099, np.float64(0.6123724356957946))
(9102, np.float64(0.6123724356957946))
(9104, np.float64(0.6123724356957946))
(9110, np.float64(0.6123724356957946))
(9112, np.float64(0.6123724356957946))
(9114, np.float64(0.6123724356957946))
(9115, np.float64(0.6123724356957946))
(9136, np.float64(0.6123724356957946))
(9150, np.float64(0.6123724356957946))
(9158, np.float64(0.6123724356957946))
(9172, np.float64(0.6123724356957946))
(9175, np.float64(0.6123724356957946))
(9282, np.float64(0.6123724356957946))
(9359, np.float64(0.6123724356957946))
(9378, np.float64(0.6123724356957946))
(9492, np.float64(0.6123724356957946))
(9529, np.float64(0.6123724356957946))
(9541, np.float64(0.6123724356957946))
(9560, np.float64(0.6123724356957946))
(9617, np.float64(0.6123724356957946))
(1592, np.float64(0.5477225575051662))
(3235, np.float64(0.5477225575051662))

In [44]:
for index, similarity_score in similar_app[1:11]:
    print(final_df.iloc[index, 0])

pluto tv - it’s free tv
tubi tv - free movies & tv
vigo lite
google play games
hotstar
peers.tv: broadcast tv channels first, match tv, tnt ...
spectrum tv
dstv now
ivi - movies and tv shows in hd
viki: asian tv dramas & movies

In [45]:
def recommend(app_name):
        app_index = final_df[final_df["App"] == app_name].index[0]
        distances = similarity[app_index]
    
        similar_app = sorted(list(enumerate(distances)), reverse=True,key=lambda x: x[1])
         

        for index, similarity_score in similar_app[1:11]:
            print(final_df.iloc[index,0])

In [57]:
recommend("twitter")

topbuzz: breaking news, videos & funny gifs
twitter
onet - news, weather, sport
world newspapers
sync for reddit
baconreader for reddit
dh news
newsdog - latest news, breaking news, local news
native entertainment magazine - issue # 1
q alerts: qanon drop notifications, research +++

In [47]:
## AS OF NOW, THE CODE IS WORKING BUT THERE IS A PROBLEM WITH SIMILARITY, WHICH IS WHY IT IS NOT RECOMMENDING CORRECTLY
## DEBUG THE CODE, CHECK FROM WHERE THE PROBLEM IS OCCURING